### ISSUE TITLE
Select Hue group

### ISSUE THREAD

**Issue by craftbyte** [JasonPuglisi/lastfm-now#1]
It would be nice to be able to select a hue group.
Possibly the easiest solution would be to map the number keys, but some people have more than 10 groups.

**Comment by JasonPuglisi** [comment]
Glad to see someone else is taking advantage of the Hue integration, I
wasn't sure if I was the only one. This sounds like a good idea, so I'll
try to add some more advanced control when I have time. I just have three
Hue bulbs in a lamp, so I didn't bother adding group control and stuff.

**Comment by craftbyte** [comment]
When you have your whole house on Hues and this changes them, it's a lot of questions from family :D But I have a few bulbs in 3 rooms, so I saw that this was happening and it would be a nice addition.

The simplest solution probably would be to make a group called artwork or something and update that one and let the user use their app to add bulbs to it.

**Comment by JasonPuglisi** [comment]
Heh yeah I knew this would be an issue, but I didn't worry about it since I
wasn't sure if it affected anyone.

**Comment by bumpcty** [comment]
I just found your reddit post and want to say this is awesome. I've been using Sonos Moodring for Hue integration, but your site is a lot easier to set up.

The groupings would be convenient. I have some light strips for ambient lighting that are on scheduled color scenes. But as it is, thank you for creating this.

**Comment by JasonPuglisi** [comment]
Glad you like it bumpcty, I finally decided to take care of this so craftbyte can stop his eternal wait and you can use it too. As per the README, the setup is now at /now/app/hue (https://www.wagnaria.xyz/now/app/hue), and it will allow you to select the rooms to control at the end.

Groups are called rooms now according to Hue, so that's what I went with even though I don't really prefer the term.

<3
