### ISSUE TITLE
Ability to disable background

### ISSUE THREAD

**Issue by craftbyte** [JasonPuglisi/lastfm-now#2]
It would be noce to be possible to disable the background art, I plan to use this maybe for streaming and using this with a stream overlay would be really nice, maybe add some motion.
I will try to work on the background toggle or figure out how to get rid of it in OBS and make a PR.

**Comment by JasonPuglisi** [comment]
Background toggle should be easy enough, but I'm against motion. I might
consider a toggle for it.

**Comment by craftbyte** [comment]
At least a fading effect for the text and merge for the image would be better than a cut :)

**Comment by JasonPuglisi** [comment]
Oh yeah, that kind of motion I'm alright with. Background art actually has
fade applied through CSS, but it only works in WebKit browsers as far as I
know. I run it in Safari because I know it works there.

**Comment by craftbyte** [comment]
Yeah, I saw that in Chrome as well, still need to fade the lower image and
text though.

**Comment by JasonPuglisi** [comment]
I decided to add this toggle in the URL using a query string. I didn't want to add it as a hotkey and make the help menu any larger, especially since I don't see this feature being used very much. To disable background art, you can append `?nobg=true` to the URL. I also added instructions to the readme.

As for fading in the lower right corner, I'm going to stick with my original decision to have hard cuts. I tried it both ways a few times since the beginning, and having it update instantly makes the page feel more responsive in my opinion.
