### ISSUE TITLE
Album Artwork Content Doesn't load after spotify Adverts - Safari

### ISSUE THREAD

**Issue by roraigh** [JasonPuglisi/lastfm-now#4]
while the text updates the pictures goes blank. 
both the small and large dont load. 

but only what seems to be an adverts, if a song is played and the next comes on the picture load fine, but if theres an advert inbetween they dont

when you refresh the page the pictures update.

**Comment by JasonPuglisi** [comment]
I've experienced this before with any pause in music activity, not necessarily just adverts. I made some changes that I thought fixed this a while ago, but I guess not. Maybe I'll set up a second (non-premium) Spotify account to test this more easily.

**Comment by JasonPuglisi** [comment]
I wasn't able to reproduce this because I made a free account but wasn't able to get Spotify to give me any ads (maybe I wasn't listening long enough). However, I redid a lot of my code in the last commit, and the cover art fetching makes a lot more sense now. It should work in cases like this. Feel free to comment if you're still experiencing issues though.
